language: php

php:
  - 7.0
addons:
  chrome: beta

sudo: false

matrix:
  fast_finish: true
  include:
    - env: TEST_SUITE=Composer
    - env: TEST_SUITE=PHPCS
    - env: TEST_SUITE=Behat

services:
  - mysql

before_install:
  # Composer Configurations.
  # Set php memory limit to -1 so composer update will not fail
  - export COMPOSER_MEMORY_LIMIT=-1
  # To enforce throwing an error and stopping package installation/update immediately
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  # Installing hirak/prestissimo allows composer to parallelise downloads which speeds up the composer install.
  - composer --verbose self-update
  - composer global require hirak/prestissimo

  # Print info and prepare for the installation
  - |
    if [ "$TEST_SUITE" = "Behat" ] || [ "$TEST_SUITE" = "PHPCS" ]; then
      echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      phpenv config-rm xdebug.ini
      composer --version
      google-chrome --version
      mysql -e "create database IF NOT EXISTS test;" -uroot
      wget --no-check-certificate https://drupalnorge.no/sanitized.db
    fi

install:
  - cd $TRAVIS_BUILD_DIR
  - if [ "$TEST_SUITE" = "Composer" ]; then composer install --no-dev; fi
  - if [ "$TEST_SUITE" = "Behat" ] || [ "$TEST_SUITE" = "PHPCS" ]; then ./scripts/travis.sh; fi

script:
  - if [ "$TEST_SUITE" = "PHPCS" ]; then composer phpcs; fi
  - if [ "$TEST_SUITE" = "Behat" ]; then composer sbehat; fi
